strawberryfield.strawberry_keynameprovider.*:
  type: config_entity
  label: 'Strawberry Key Name Providers config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    pluginid:
      type: string
      label: 'Plugin ID'
    pluginconfig: {  }
    active:
      type: boolean
      label: 'Whether this plugin is active or not'

